version: 2

workflows:
  build:
    jobs:
      - build
  hourly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: 0 0 17/1 ? * * *
          filters:
            branches:
              only:
                - master

jobs:
  build:
    working_directory: ~/seapig
    resource_class: large
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: Install
          command: npm ci
      - run:
          name: Checks
          command: npm run prepublish
