version: 2.1

workflows:
  build_workflow:
    jobs:
      - build
  hourly:
    jobs:
      - build
      - build_large
    triggers:
      - schedule:
          cron: 0 * * * *
          filters:
            branches:
              only:
                - master

jobs:
  build_large:
    working_directory: ~/seapig
    resource_class: large
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: Install
          command: npm ci
      - run:
          name: Checks
          command: npm run prepublish
  build:
    working_directory: ~/seapig
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: Install
          command: npm ci
      - run:
          name: Checks
          command: npm run prepublish
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
