version: 2.1

workflows:
  build_workflow:
    jobs:
      - build
  

jobs:
  build:
    working_directory: ~/seapig
    resource_class: large
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: Install
          command: npm ci
      - run:
          name: Checks
          command: npm run prepublish
