name: CI

on: [push]

jobs:
  build:
    name: Unit tests, lint and builds    
    timeout-minutes: 30
    runs-on: ubuntu-latest    
    steps:
      - name: "Install modules"
        run: npm install
      - name: "Lint"
        run: npm run lint
      - name: "Test"
        run: npm run test
      - name: "Build"
        run: npm run build